# Minimal golangci-lint configuration for projects without Go source files
# This allows the configuration to exist without errors

linters:
  enable:
    - unused
    - ineffassign
    - misspell
    - goimports
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck

issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - gosec

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/RuneORakeie/tflint-ruleset-fabric
  revive:
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true
