version: 2

linters:
  enable:
    - unused
    - ineffassign
    - misspell
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck
  settings:
    govet:
      enable:
        - shadow
    revive:
      severity: warning
      rules:
        - name: unused-parameter
          disabled: true

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/RuneORakeie/tflint-ruleset-fabric

linters:
  exclusions:
    rules:
      - path: "_test\\.go$"
        linters:
          - gosec