linters:
  enable:
    - unused
    - ineffassign
    - misspell
    - goimports
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocritic
    - godot
    - godox
    - goheader
    - goprintffuncname
    - gosec
    - gosmopolitan
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - sloglint
    - tagliatelle
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - gosec
        - dupl

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/RuneORakeie/tflint-ruleset-fabric
  revive:
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true
