# .goreleaser.yml - Automated Release Configuration

version: 2

before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Sha1ver={{ .Commit }}
    binary: tflint-ruleset-fabric

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: checksum

release:
  github:
    owner: RuneORakeie
    name: tflint-ruleset-fabric
  prerelease: auto
  draft: false
  mode: replace
  name_template: "v{{ .Version }}"

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat(\\(.+\\))?!?:.+$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix(\\(.+\\))?!?:.+$"
      order: 1
    - title: Documentation
      regexp: "^.*docs(\\(.+\\))?!?:.+$"
      order: 2
    - title: Dependency updates
      regexp: "^.*chore(\\(deps.*\\))?!?:.+$"
      order: 3
    - title: Other work
      order: 999
